In [1]:
import numpy as np

In [2]:
arr1 = np.array([])
arr1

array([], dtype=float64)

In [3]:
type(arr1)

numpy.ndarray

In [4]:
# creating array from list
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
a = np.array(my_list)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
x = (1,2,3,4,5)
print(x)

(1, 2, 3, 4, 5)


In [8]:
type(x)

tuple

In [9]:
# convert tuple to numpy array
a1 = np.asarray(x)
print(type(a1))
print(a1)


<class 'numpy.ndarray'>
[1 2 3 4 5]


In [10]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [42]:
my_matrix = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
my_matrix

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]

In [43]:
arr3d = np.array(my_matrix)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [44]:
arr3d.shape

(1, 3, 4)

In [11]:
b = np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print('The Dimension of array',b.ndim)

The Dimension of array 2


In [13]:
print('The size of array:',b.size)

The size of array: 12


In [14]:
print('The datatype of element',b.dtype)

The datatype of element int32


In [15]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [16]:
print('The Shape',b.shape)

The Shape (3, 4)


In [17]:
li = ['as',3,5,7.9]
li

['as', 3, 5, 7.9]

In [18]:
ar = np.array(li)
ar

array(['as', '3', '5', '7.9'], dtype='<U32')

## Arithmetic operations on Array

In [20]:
arr =np.arange(0,20)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [23]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [24]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
arr / arr 

C:\Users\praga\AppData\Local\Temp\ipykernel_24896\2663351161.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

In [27]:
arr % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1],
      dtype=int32)

In [28]:
1/arr # reciprocal

C:\Users\praga\AppData\Local\Temp\ipykernel_24896\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

## Universal  Array Function

In [29]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np.add(arr,3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [31]:
np.sum()

TypeError: sum() missing 1 required positional argument: 'a'

In [32]:
np.sum(arr)

190

In [35]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [36]:
np.cbrt(arr)

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105,
       1.70997595, 1.81712059, 1.91293118, 2.        , 2.08008382,
       2.15443469, 2.22398009, 2.28942849, 2.35133469, 2.41014226,
       2.46621207, 2.5198421 , 2.57128159, 2.62074139, 2.66840165])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [39]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [40]:
np.tan(arr)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01])

In [41]:
np.log(arr)

C:\Users\praga\AppData\Local\Temp\ipykernel_24896\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

## Pandas

In [45]:
import pandas as pd

### series

In [47]:
d = pd.Series()
d

Series([], dtype: object)

In [48]:
type(d)

pandas.core.series.Series

In [50]:
#creating series with one element
d = pd.Series(17)
d

0    17
dtype: int64

In [51]:
## creating series using tuple
t = (10,11,12)
d = pd.Series(t)
d

0    10
1    11
2    12
dtype: int64

In [52]:
## dreating series using list
l1 = [45,78,56,445,78]
d = pd.Series(l1)
d

0     45
1     78
2     56
3    445
4     78
dtype: int64

In [53]:
## Creating series with array
import numpy as np
arr = np.array([1,2,3,4])
d1 =pd.Series(arr)
d1

0    1
1    2
2    3
3    4
dtype: int32

In [55]:
## Using dictionary
d = {'a':1,'b':2,'c':3,'d':4}
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [56]:
b = pd.Series(d)
b

a    1
b    2
c    3
d    4
dtype: int64

## DataFrame 

In [58]:
## empty datatype
d = pd.DataFrame()
d

Empty DataFrame
Columns: []
Index: []

In [59]:
type(d)

pandas.core.frame.DataFrame

In [60]:
# Dataframe using list
data = [['abc',1],['def',2],['ghi',3],['hij',4],['kim',5]]

In [61]:
a =pd.DataFrame()
a

Empty DataFrame
Columns: []
Index: []

In [62]:
data = {'name':['a','b','c','d','e','f'],'age':[45,12,48,25,12,56]}

In [63]:
d = pd.DataFrame(data)
d

name  age
0    a   45
1    b   12
2    c   48
3    d   25
4    e   12
5    f   56

In [64]:
data = [['Alex',10,'Maths'],['Bob',12,'Science'],['Kelly',15,'Eco'],['Boris',14,'Geo'],['Ken',18,'English']]

In [66]:
d =pd.DataFrame(data,columns = ['Name','Age','Subject'])
d

Name  Age  Subject
0   Alex   10    Maths
1    Bob   12  Science
2  Kelly   15      Eco
3  Boris   14      Geo
4    Ken   18  English

In [67]:
d['Name']

0     Alex
1      Bob
2    Kelly
3    Boris
4      Ken
Name: Name, dtype: object

In [68]:
d[['Name','Subject']]

Name  Subject
0   Alex    Maths
1    Bob  Science
2  Kelly      Eco
3  Boris      Geo
4    Ken  English

In [73]:
import seaborn as sns

In [72]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [75]:
data =sns.load_dataset('iris')

In [76]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [77]:
type(data)

pandas.core.frame.DataFrame

In [78]:
# first 5 rows
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [80]:
#last 5 rows
data.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [81]:
data.shape

(150, 5)

In [82]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [83]:
data.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [86]:
data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [88]:
data.median()

TypeError: could not convert string to float: 'setosa'

In [89]:
data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].median()

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [90]:
data.sepal_length.mean()

5.843333333333334

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [92]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [93]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [94]:
data.describe(include = 'O')

species
count      150
unique       3
top     setosa
freq        50

In [95]:
data.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [97]:
data.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

### Task :
#### Explore tips dataset from seaborn libray and perform same operation

In [98]:
import seaborn as sns

In [99]:
data =sns.load_dataset('tips')